# Title shown in Application Information tab.
title: "RedBull Honda Racing Analytics Hands-on Lab Environment"
# Sub Title shown in Application Information tab.
description: "RedBull Honda Racing Analytics Hands-on Lab Environment"
schemaVersion: 1.1.0
version: "1.0"
locale: "en"
variableGroups:
  - title: "Hidden"
    variables:
      - tenancy_ocid
      - user_ocid
      - region
      - fingerprint
      - private_key_path
      - private_key_password
      - private_key
      - region
      - compartment_ocid
    visible: false
  - title: "Configuration"
    variables:
      - redbull_compartment
      - free_tier_compute
      - ssh_public_key

variables:
  free_tier_compute:
    type: boolean
    title: "Use Always-Free Shape?"
    description: "Should an always free-tier compute shape be used?  If not selected, a shape that's eligible in a trial period or a paid account is used."
    required: true
    default: false
  redbull_compartment:
    type: string
    title: "Compartment Name"
    description: "The name of the compartment that will be created."
    required: true
    default: "redbullhol"
  ssh_public_key:
    title: "Compute SSH Public Key"
    description: "The public to install on the compute for SSH access."
    type: oci:core:ssh:publickey
    required: true